Trying to follow documentation at https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_a_new_expectation_suite_without_the_cli.html
getting_started_tutorial_final_v3_api$ python example_without_cli.py
Traceback (most recent call last):
  File "/usr/local/google/home/jdimatteo/dev/ge_tutorials_fork/getting_started_tutorial_final_v3_api/example_without_cli.py", line 17, in <module>
    validator = context.get_validator(batch_request=batch_request, expectation_suite=suite)
  File "/usr/local/google/home/jdimatteo/Desktop/great_expectations_custom/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 1680, in get_validator
    self.get_batch(
  File "/usr/local/google/home/jdimatteo/Desktop/great_expectations_custom/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 1417, in get_batch
    return self._get_batch_v3(
  File "/usr/local/google/home/jdimatteo/Desktop/great_expectations_custom/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 1239, in _get_batch_v3
    raise ValueError(
ValueError: Got 0 batches instead of a single batch.